Add document to join Mattermost
OpenTermsArchive/docs pull request #149
Opened 2024-11-13 13:34 UTC by Aysha-py

The link to the images in the document is currently broken. However, it is available on the cloud. Can someone please help fix this or provide assistance?

You can find the images [here](https://cloud.opentermsarchive.org/index.php/apps/files/?dir=/Workspace&fileid=1390)

2024-11-13 14:52 UTC, clementbiron commented
Hello @Aysha-py, 

Thanks for your work!

I'll take care of correcting the links to the images but the url you provide won't let me retrieve them. Can you check that the link and/or share configuration is correct? If need be, let's call to discuss it together.

2024-11-13 14:57 UTC, MattiSG commented
Here is the [direct file link](https://cloud.opentermsarchive.org/index.php/apps/files/?dir=/Workspace&openfile=1466).

2024-11-13 15:38 UTC, clementbiron commented
Thanks @MattiSG

2024-11-14 03:48 UTC, Aysha-py commented
Thanks @MattiSG for providing the file link and @clementbiron for adding the images.

2024-11-18 09:11 UTC, clementbiron reviewed
Thanks for your work! 

I've made the necessary corrections to get the images working.

I know @MattiSG will be doing a review for you in the next few days.

2024-11-18 09:58 UTC, MattiSG requested changes
Looks good, thank you! 👍 
I made some suggestions to correct a few typos and to unify the markup.

2024-11-18 09:58 UTC, MattiSG commented on content/community/how-to-join-mattermost.md
> +   ![Joinning Channels on Mattermost]({{< relref "." >}}joinning-channels.png)
```suggestion
   ![Joining Channels on Mattermost]({{< relref "." >}}joinning-channels.png)
```

2024-11-20 08:53 UTC, MattiSG approved these changes

2024-11-20 08:53 UTC, merged