Added the troubleshooting and communication section for the mailto pr…
OpenTermsArchive/docs pull request #66
Opened 2023-07-31 12:05 UTC by emmanuellar

…oblem

2023-08-16 08:14 UTC, MattiSG requested changes
We had discussed this text together, could you please take into account the edits we had mentioned? Thank you  🙂 

In particular:
- The context of using the graphical user interface tool is missing.
- In context, thanking for contribution is out of place: think of the whole page and the user journey. It is a good idea to thank for contributions, but this should be at the top of the page (or in a separate pull request).

2023-08-28 13:20 UTC, MattiSG requested changes
Thank you @emmanuellar! I will handle the syntax errors that block merging, and will rewrite some of the content to unify its style with the rest of the page 🙂

2023-08-28 13:21 UTC, MattiSG approved these changes

2023-08-28 13:26 UTC, merged

2023-08-28 13:36 UTC, emmanuellar commented
Thank you for handling the syntax error. I see it's merged now. yay! 💃